#!/usr/bin/env ansible-playbook
---
- name: 'Born2beroot debian setup'
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  tasks:

    - name: 'Update installed packages'
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        clean: yes

    - name: 'Install openssh-server package'
      ansible.builtin.apt:
        name: openssh-server

    - name: 'Start and enable ssh service'
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: yes

    - name: 'Set the sshd config settings'
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#+{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
      loop:
        - { key: 'Port', value: '4242' }
        - { key: 'PermitRootLogin', value: 'no' }

    - name: 'Restart ssh service'
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: 'Install ufw package'
      ansible.builtin.apt:
        name: ufw

    - name: 'Enable ufw and allow ssh port'
      ansible.builtin.command:
        cmd: "/usr/sbin/ufw {{ item }}"
      loop:
        - 'allow proto tcp to any port 4242 comment "allow-ssh"'
        - '--force enable'

    - name: 'Set hostname'
      ansible.builtin.hostname:
        name: abenamar42

    - name: 'Replace old hostname'
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1\tabenamar42"

    - name: 'Udpate password policy to respect 42 guidelines'
      ansible.builtin.command:
        cmd: "/usr/bin/chage -M 30 -m 2 -W 7 {{ item }}"
      loop:
        - 'abenamar'
        - 'root'

    - name: 'Install libpam-cracklib package'
      ansible.builtin.apt:
        name: libpam-cracklib

    - name: 'Edit /etc/pam.d/common-password to respect 42 guidelines'
      ansible.builtin.lineinfile:
        path: /etc/pam.d/common-password
        insertbefore: '^# and here are more per-package modules'
        line: "\npassword required pam_cracklib.so minlen=10 ucredit=-1 lcredit=-1 dcredit=-1 maxrepeat=3 reject_username difok=7 enforce_for_root\n"

    - name: 'Install sudo package'
      ansible.builtin.apt:
        name: sudo

    - name: 'Edit /etc/sudoers'
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^Defaults(\\s+){{ item.key }}"
        insertafter: '^Defaults'
        line: "Defaults\t{{ item.value }}"
      loop:
        - { key: 'passwd_tries', value: 'passwd_tries=3' }
        - { key: 'badpass_message', value: 'badpass_message="Oh no! You have not really your sudo password, huh ??"' }
        - { key: 'log_input', value: 'log_input' }
        - { key: 'log_output', value: 'log_output' }
        - { key: 'iolog_dir', value: 'iolog_dir="/var/log/sudo"' }
        - { key: 'requiretty', value: 'requiretty' }
        - { key: 'secure_path', value: 'secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"' }

    - name: 'Ensure user42 and sudo group exist'
      ansible.builtin.group:
        name: "{{ item }}"
      loop:
        - 'user42'
        - 'sudo'

    - name: 'Update user to respect to 42 guidelines'
      ansible.builtin.user:
        name: abenamar
        groups: user42,sudo
        password: "{{ 'Dummy1user' | password_hash('sha512') }}"

    - name: 'Update root to respect to 42 guidelines'
      ansible.builtin.user:
        name: root
        password: "{{ 'Dummy1admin' | password_hash('sha512') }}"

    - name: 'Download monitoring.sh'
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/abdelbenamara/Born2beRoot/main/monitoring.sh'
        dest: '/usr/local/bin/monitoring.sh'
        mode: '0111'

    - name: 'Cron monitoring.sh'
      ansible.builtin.cron:
        name: 'wall monitoring job'
        minute: "*/10"
        job: '/usr/local/bin/monitoring.sh'

    - name: 'Bonus #1 : Install lvm2 package'
      ansible.builtin.apt:
        name: lvm2

    - name: 'Bonus #1 : Resize debian-vg home'
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - '/usr/bin/umount /home'
        - '/usr/sbin/e2fsck -fy /dev/debian-vg/home'
        - '/usr/sbin/resize2fs /dev/debian-vg/home 300M'
        - '/usr/sbin/lvreduce -f -L 300M /dev/debian-vg/home'
        - '/usr/sbin/resize2fs /dev/debian-vg/home'

    - name: 'Bonus #1 : Create new debian-vg logical volumes'
      ansible.builtin.command:
        cmd: "/usr/sbin/lvcreate -n {{ item.key }} -L {{ item.value }} debian-vg"
      loop:
        - { key: 'var', value: '2G' }
        - { key: 'srv', value: '200M' }
        - { key: 'tmp', value: '500M' }
        - { key: 'var-log', value: '700M' }

    - name: 'Bonus #1 : Create new ext4 filesystems'
      ansible.builtin.command:
        cmd: "/usr/sbin/mkfs.ext4 /dev/debian-vg/{{ item }}"
      loop:
        - 'var'
        - 'srv'
        - 'tmp'
        - 'var-log'

    - name: 'Bonus #1 : Edit /etc/fstab to add new filesystems informations'
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "/dev/debian-vg/{{ item.key }} {{ item.value }} ext4 defaults 1 2"
        backup: yes
      loop:
        - { key: 'var', value: '/var' }
        - { key: 'srv', value: '/srv' }
        - { key: 'tmp', value: '/tmp' }
        - { key: 'var-log', value: '/var/log' }

    - name: 'Bonus #1 : Ensure new mounting points exists'
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop:
        - '/var'
        - '/srv'
        - '/tmp'
        - '/var/log'

    - name: 'Bonus #1 : Backup data in future mounting points'
      ansible.builtin.command:
        cmd: "/usr/bin/cp -a {{ item }}/. {{ item }}.ori"
      loop:
        - '/var'
        - '/srv'
        - '/tmp'

    - name: 'Bonus #1 : Mount /home, /var, /srv and /tmp filesystems'
      ansible.builtin.command:
        cmd: "/usr/bin/mount {{ item }}"
      loop:
        - '/home'
        - '/var'
        - '/srv'
        - '/tmp'

    - name: 'Bonus #1 : Recover data in /var, /srv and /tmp'
      ansible.builtin.command:
        cmd: "/usr/bin/cp -a {{ item }}.ori/. {{ item }}"
      loop:
        - '/var'
        - '/srv'
        - '/tmp'

    - name: 'Bonus #1 : Mount /var/log filesystem'
      ansible.builtin.command:
        cmd: "/usr/bin/mount /var/log"

    - name: 'Bonus #1 : Recover data in /var/log'
      ansible.builtin.command:
        cmd: "/usr/bin/cp -a /var.ori/log/. /var/log"

    - name: 'Bonus #1 : Delete temporary directories used to mount new filesystems'
      ansible.builtin.file:
        path: "{{ item }}.ori"
        state: absent
      loop:
        - '/var'
        - '/srv'
        - '/tmp'
        
    - name: 'Bonus #2 : Install lighttpd package'
      ansible.builtin.apt:
        name: lighttpd

    - name: 'Bonus #2 : Start and enable lighttpd service'
      ansible.builtin.service:
        name: lighttpd
        state: started
        enabled: yes

    - name: 'Bonus #2 : Allow http port'
      ansible.builtin.command:
        cmd: '/usr/sbin/ufw allow proto tcp to any port 80 comment "allow-http"'

    - name: 'Bonus #2 : Install php7.4 php7.4-fpm php7.4-mysql php7.4-cli php7.4-curl php7.4-xml php-json php-zip php-mbstring php-gd php-intl and php-cgi packages'
      ansible.builtin.apt:
        name:
        - 'php7.4'
        - 'php7.4-fpm'
        - 'php7.4-mysql'
        - 'php7.4-cli'
        - 'php7.4-curl'
        - 'php7.4-xml'
        - 'php-json'
        - 'php-zip'
        - 'php-mbstring'
        - 'php-gd'
        - 'php-intl'
        - 'php-cgi'

    - name: 'Bonus #2 : Start and enable php7.4-fpm service'
      ansible.builtin.service:
        name: php7.4-fpm
        state: started
        enabled: yes

    - name: 'Bonus #2 : Edit php7.4-fpm configuration file'
      ansible.builtin.lineinfile:
        path: /etc/php/7.4/fpm/pool.d/www.conf
        regexp: '^listen ='
        line: 'listen = 127.0.0.1:9000'

    - name: 'Bonus #2 : Edit lighttpd 15-fastcgi-php configuration file'
      ansible.builtin.lineinfile:
        path: /etc/lighttpd/conf-available/15-fastcgi-php.conf
        regexp: "^(\\s+){{ item.key }}"
        line: "\\1{{ item.value }}"
        backrefs: yes
      loop:
        - { key: '"bin-path" =>', value: '"host" => "127.0.0.1",' }
        - { key: '"socket" =>', value: '"port" => "9000",' }

    - name: 'Bonus #2 : Enable php-fpm on lighttpd'
      ansible.builtin.command:
        cmd: "/usr/sbin/lighty-enable-mod {{ item }}"
      loop:
        - 'fastcgi'
        - 'fastcgi-php'

    - name: 'Bonus #2 : Restart lighttpd and php7.4-fpm services'
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - 'lighttpd'
        - 'php7.4-fpm'

    - name: 'Bonus #2 : Install mariadb-server package'
      ansible.builtin.apt:
        name: mariadb-server

    - name: 'Bonus #2 : Start and enable mysql service'
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: 'Bonus #2 : Secure MariaDB installation and create new database and user for WordPress'
      ansible.builtin.command:
        cmd: "/usr/bin/mysql -e \"{{ item }};\""
      loop:
        - "DELETE FROM mysql.user WHERE User=''"
        - "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
        - "DROP DATABASE IF EXISTS test"
        - "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\\\_%'"
        - "CREATE DATABASE wordpress"
        - "GRANT ALL PRIVILEGES on wordpress.* TO 'wordpress_user'@'localhost' IDENTIFIED BY 'wordpress_pss123'"
        - "FLUSH PRIVILEGES"

    - name: 'Bonus #2 : Restart mysql service'
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: 'Bonus #2 : Download wordpress archive in /tmp'
      ansible.builtin.get_url:
        src: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/latest.tar.gz'

    - name: 'Bonus #2 : Extract wordpress archive and move it to /var/www/html'
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - '/usr/bin/tar -xvzf /tmp/latest.tar.gz --directory /var/www/html'
        - '/usr/bin/mv /var/www/html/wordpress/ /var/www/html/wordpress.42bonus.lan'

    - name: 'Bonus #2 : Delete wordpress archive from /tmp'
      ansible.builtin.file:
        path: '/tmp/latest.tar.gz'
        state: absent

    - name: 'Bonus #2 : Ensure /var/www/html has recursively correct ownership and rights'
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: 'Bonus #2 : Create folder dedicated to virtual hosts in Lighttpd'
      ansible.builtin.file:
        path: /etc/lighttpd/vhosts.d
        state: directory

    - name: 'Bonus #2 : Edit /etc/lighttpd/lighttpd.conf to add new virtual hosts'
      ansible.builtin.lineinfile:
        path: /etc/lighttpd/lighttpd.conf
        line: 'include_shell "cat /etc/lighttpd/vhosts.d/*.conf"'

    - name: 'Bonus #2 : Create /etc/lighttpd/vhosts.d/wordpress.42bonus.lan.conf'
      ansible.builtin.lineinfile:
        path: /etc/lighttpd/vhosts.d/wordpress.42bonus.lan.conf
        line: "{{ item }}"
      loop:
        - '$HTTP["host"] =~ "(^|.)wordpress.42bonus.lan$" {'
        - 'server.document-root = "/var/www/html/wordpress.42bonus.lan"'
        - 'server.errorlog = "/var/log/lighttpd/wordpress.42bonus.lan-error.log"'
        - 'accesslog.filename = "/var/log/lighttpd/wordpress.42bonus.lan-access.log"'
        - 'url.rewrite-final = ("^/(.*.php)" => "$0", "^/(.*)$" => "/index.php/$1" )'
        - '}'

    - name: 'Bonus #2 : Restart lighttpd service'
      ansible.builtin.service:
        name: lighttpd
        state: restarted

    - name: 'Remove useless packages from the cache'
      ansible.builtin.apt:
        autoclean: yes

    - name: 'Remove dependencies that are no longer required'
      ansible.builtin.apt:
        autoremove: yes
